### PR TITLE
provide a better example of option formatting.

### PR DESCRIPTION
**Pull request by majormoses**
make it slightly clearer about dependencies.
remove link to codeship as its not used anymore.

Signed-off-by: Ben Abrams <me@benabrams.it>

### CODE REVIEW

**Review by eheydrick — APPROVED** [review]
👍 Can you send this update to https://github.com/sensu-plugins/documentation/blob/master/docs/developer_guidelines.md too. That is supposed to be the source for the docs part of the site and I'd like to keep it in sync.

**Comment by majormoses** [comment]
@eheydrick I don't like the idea of 2 places for the same thing...should we just make this a link then to the doc stuff?

**Comment by majormoses** [comment]
committed the same changes to master in https://github.com/sensu-plugins/documentation/commit/486a60caf7e5a0a6f6c7722591de6fec5ab03cf9

**Comment by eheydrick** [comment]
I don't like 2 places either, it needs work for sure. The build deploy for the docs part of the site was on codeship but it broke at some point. I've made an issue for rationalizing the site. https://github.com/sensu-plugins/documentation/issues/10.

**Pull request merged**
